# Required connection configs for Kafka producer, consumer, and admin
spring:
  kafka:
    bootstrap-servers: pkc-41p56.asia-south1.gcp.confluent.cloud:9092
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='${KAFKA_USERNAME}' password='${KAFKA_PASSWORD}';
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: ${SR_API_KEY}:${SR_API_SECRET}
      schema:
        registry:
          url: https://psrc-4nxg3.australia-southeast1.gcp.confluent.cloud
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: spring-producer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    streams:
      replication-factor: 3
      application-id: spring-streams
